#ifndef __TESTCASE_H_
#define __TESTCASE_H_

#define TESTID_CACHE_INITTEST 0
#define TESTID_CACHE_INITTEST_JUMP 1
#define TESTID_CACHE_NONJUMP_ARRAYTOARRAY_CPY 2
#define TESTID_CACHE_NONJUMP_ARRAYTOVAR_CPY 3
#define TESTID_STACKTEST_SCHEDPOINT_1 4
#define TESTID_HEAPTEST 5
#define TESTID_STACKTEST_VARYINGSIZES 6
#define TESTID_CODESECTION_INTEGRITYTEST 8
#define TESTID_QOSTEST 9

#endif
